name: Sync Upstream
on:
  schedule:
    - cron: "0 0 */5 * *"  # 每5天同步一次
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Fork
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.repos.mergeUpstream({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main'
              });
              console.log('Synced successfully!');
            } catch (error) {
              core.setFailed('Sync failed: ' + error.message);
            }
